export const appCopy = {
  appName: "Sticker Smith",
  actions: {
    addFiles: "Add Files",
    addFolder: "Add Folder",
    apply: "Apply",
    cancel: "Cancel",
    clear: "Clear",
    clearSelection: "Clear Selection",
    close: "Close",
    connectTelegram: "Connect Telegram",
    manageTelegram: "Manage Telegram",
    copyFolderHere: "Copy Folder Here",
    confirm: "Confirm",
    delete: "Delete",
    downloadMedia: "Download Media",
    downloadingMedia: "Downloading…",
    import: "Import",
    editEmojis: "Edit Emojis",
    export: "Export",
    logout: "Logout",
    newPack: "New pack",
    open: "Open",
    openFolder: "Open Folder",
    removeIcon: "Remove icon",
    rename: "Rename",
    resetTelegram: "Reset Telegram",
    resync: "Resync",
    retryMedia: "Retry Media",
    selectAll: "Select All",
    setAsIcon: "Set as icon",
    sync: "Sync",
    push: "Push",
    pushing: "Pushing…",
    upload: "Upload",
    uploading: "Uploading…",
  },
  dialogs: {
    conversionFailed: "Some files could not be added",
    editEmojis: "Edit Emojis",
    editSelectedEmojis: "Edit Emojis for Selection",
    newPack: "New Pack",
    renamePack: "Rename Pack",
    telegramPublish: "Telegram Publish",
    telegramSetup: "Telegram Setup",
    syncWarningTitle: "Unsaved changes will be lost",
    syncWarningDescription: "Syncing will overwrite local edits in the following packs:",
    packName: "Pack name",
  },
  emptyStates: {
    noStickers: "No stickers ・ add files or a folder to get started.",
    noLocalPacks: "No local packs yet",
    noTelegramPacks: "Connect Telegram to load remote sticker packs.",
    noSelection: "Select a pack or create a new one.",
  },
  labels: {
    baseName: "Base name",
    emojiList: "Emoji list",
    exportDialogTitle: "Export",
    galleryView: "Gallery view",
    importFolderAsNewPack: "Import folder as new pack",
    listView: "List view",
    localPacks: "Local",
    noEmoji: "No emoji",
    openContainingFolder: "Open containing folder",
    stickers: "Stickers",
    stickerStatusAll: "All",
    stickerStatusDraft: "Incomplete",
    stickerStatusFailed: "Failed",
    stickerStatusModified: "Edited",
    stickerStatusReady: "Ready",
    stickerStatusSynced: "Synced",
    stickerStatusTelegram: "Telegram",
    selectedStickers: "Selected stickers",
    telegramApiHash: "API hash",
    telegramApiId: "API ID",
    telegramAccount: "Telegram account",
    telegramCode: "Login code",
    telegramConnected: "Connected",
    telegramNeedsCode: "Code required",
    stickersNeedEmoji: "No emoji",
    telegramDisconnected: "Not connected",
    telegramMirrorError: "Sync error",
    telegramMirrorNeedsUpdate: "Needs update",
    telegramMirrorSyncing: "Syncing",
    telegramMirrorUnsupported: "Unsupported",
    telegramMirrorUpToDate: "Up to date",
    telegramSyncInProgress: "Sync in progress",
    telegramNeedsPassword: "Password required",
    telegramPhoneNumber: "Phone number",
    telegramPassword: "Two-step password",
    telegramNeedsCredentials: "Credentials needed",
    telegramPacks: "Telegram",
    telegramShortNameUnset: "Short name not set",
    telegramUnsupportedPacks: "Telegram (Unsupported)",
    telegramShortName: "Short name",
    telegramTitle: "Title",
  },
  status: {
    starting: "Starting…",
  },
  tooltips: {
    converting: "Converting…",
    deletePack: "Delete pack",
    deleteTelegramPack: "Deleting Telegram sticker sets is not supported yet",
    rename: "Rename",
    syncTelegramPacks: "Sync Telegram packs",
  },
} as const;
