export const appCopy = {
  appName: "Sticker Smith",
  actions: {
    addFiles: "Add files",
    addFolder: "Add folder",
    apply: "Apply",
    cancel: "Cancel",
    clear: "Clear",
    clearSelection: "Clear selection",
    close: "Close",
    changeIcon: "Change icon",
    connectTelegram: "Connect Telegram",
    manageTelegram: "Manage Telegram",
    copyFolderHere: "Copy folder here",
    confirm: "Confirm",
    delete: "Delete",
    downloadMedia: "Download files",
    downloadingMedia: "Downloading…",
    import: "Import",
    editEmojis: "Edit emojis",
    export: "Export",
    logout: "Logout",
    newPack: "New pack",
    open: "Open",
    openFolder: "Open folder",
    removeIcon: "Remove icon",
    rename: "Rename",
    resetTelegram: "Reset Telegram",
    resync: "Refresh",
    retryMedia: "Retry files",
    selectAll: "Select all",
    setAsIcon: "Set as icon",
    sync: "Refresh from Telegram",
    push: "Update Telegram",
    pushing: "Updating Telegram…",
    upload: "Publish to Telegram",
    uploading: "Publishing…",
  },
  dialogs: {
    conversionFailed: "Some files could not be added",
    editEmojis: "Edit emojis",
    editSelectedEmojis: "Edit emojis for selection",
    newPack: "New pack",
    renamePack: "Rename pack",
    telegramPublish: "Publish to Telegram",
    telegramSetup: "Connect Telegram",
    syncWarningTitle: "Local edits will be replaced",
    syncWarningDescription: "Refreshing from Telegram will replace local edits in these packs:",
    packName: "Pack name",
  },
  emptyStates: {
    noStickers: "Add files to convert them into Telegram-ready stickers.",
    noLocalPacks: "No local packs yet",
    noTelegramPacks: "Connect Telegram, then refresh your sticker packs.",
    noSelection: "Import a folder of sticker art, or create an empty pack and add files.",
  },
  labels: {
    baseName: "Base name",
    emojiList: "Emoji list",
    editEmojisHint: "Edit emojis",
    exportDialogTitle: "Export",
    importFolderAsNewPack: "Import folder as new pack",
    localPacks: "Local",
    noEmoji: "No emoji",
    openContainingFolder: "Open containing folder",
    stickers: "Stickers",
    stickerStatusAll: "All",
    stickerStatusDraft: "Incomplete",
    stickerStatusFailed: "Failed",
    stickerStatusModified: "Edited",
    stickerStatusReady: "Ready",
    stickerStatusSynced: "Synced",
    stickerStatusTelegram: "Telegram",
    selectedStickers: "Selected stickers",
    telegramApiHash: "Telegram API hash",
    telegramApiId: "Telegram API ID",
    telegramAccount: "Telegram account",
    telegramCode: "Login code",
    telegramConnected: "Connected",
    telegramNeedsCode: "Code required",
    stickersNeedEmoji: "No emoji",
    telegramDisconnected: "Not connected",
    telegramMirrorError: "Sync error",
    telegramMirrorNeedsUpdate: "Local edits",
    telegramMirrorSyncing: "Syncing",
    telegramMirrorUnsupported: "Unsupported",
    telegramMirrorUpToDate: "Up to date",
    telegramSyncInProgress: "Sync in progress",
    telegramNeedsPassword: "Password required",
    telegramPhoneNumber: "Telegram phone number",
    telegramPassword: "Two-step password",
    telegramNeedsCredentials: "Credentials needed",
    telegramPacks: "Telegram",
    telegramShortNameUnset: "Short name not set",
    telegramUnsupportedPacks: "Telegram (Unsupported)",
    telegramShortName: "Short name",
    telegramTitle: "Title",
  },
  status: {
    starting: "Starting…",
  },
  tooltips: {
    converting: "Converting…",
    deletePack: "Delete pack",
    deleteTelegramPack: "Deleting Telegram sticker sets is not supported yet",
    rename: "Rename",
    syncTelegramPacks: "Refresh Telegram packs",
  },
} as const;
