const APP_FONT_FAMILY = [
  '"Sarasa Mono SC"',
  '"Sarasa Mono TC"',
  '"Sarasa Mono J"',
  '"Sarasa Mono K"',
  '"Noto Sans Mono CJK SC"',
  '"Noto Sans Mono CJK TC"',
  '"Noto Sans Mono CJK JP"',
  '"Noto Sans Mono CJK KR"',
  '"Noto Sans CJK SC"',
  '"Noto Sans CJK TC"',
  '"Noto Sans CJK JP"',
  '"Noto Sans CJK KR"',
  '"Cascadia Mono"',
  '"SFMono-Regular"',
  "ui-monospace",
  "monospace",
].join(", ");

export const appTokens = {
  colorScheme: "dark",
  colors: {
    primary: "#60a5fa",
    background: {
      app: "#09090b",
      surface: "#111118",
    },
    text: {
      primary: "#e2e8f0",
      secondary: "#94a3b8",
      contrast: "#000000",
      inverseMuted: "rgba(255,255,255,0.8)",
    },
    border: {
      subtle: "rgba(255, 255, 255, 0.08)",
    },
    overlay: {
      mediaLabel: "rgba(0,0,0,0.55)",
    },
    error: "#f87171",
  },
  typography: {
    fontFamily: APP_FONT_FAMILY,
    monoFontFamily: "ui-monospace, monospace",
    fontSize: 13,
    fontSizes: {
      overline: "0.68rem",
      caption: "0.75rem",
      secondaryCaption: "0.72rem",
      body: "0.8rem",
      bodyCompact: "0.78rem",
      bodyDefault: "0.825rem",
      subtitle: "0.925rem",
      dialogTitle: "0.95rem",
      assetKind: "0.65rem",
      assetLabel: "0.6rem",
    },
    fontWeights: {
      regular: 400,
      medium: 600,
      bold: 700,
    },
    letterSpacing: {
      tight: "-0.01em",
      overline: "0.08em",
      chip: "0.04em",
    },
  },
  radii: {
    control: 6,
    panel: 8,
    card: 12,
    small: 4,
    thumbnail: 6,
    round: "50%",
  },
  layout: {
    sidebarWidth: 240,
    panelHeaderMinHeight: 48,
    tabsMinHeight: 40,
    fileGridMinWidth: 96,
    squareAspectRatio: "1 / 1",
    window: {
      width: 1600,
      height: 980,
      minWidth: 1200,
      minHeight: 720,
    },
  },
  sizes: {
    thumbnail: 20,
    fileTypeIcon: 28,
    sidebarBrandIcon: 18,
    panelActionIcon: 17,
    actionIcon: 16,
    compactActionIcon: 15,
    badge: 16,
    badgeIcon: 10,
    toggleHeight: 28,
    progressHeight: 3,
    contextMenuWide: 170,
    contextMenuNarrow: 160,
  },
  copy: {
    appName: "Sticker Smith",
    actions: {
      addFiles: "Add Files",
      addFolder: "Add Folder",
      cancel: "Cancel",
      close: "Close",
      connectTelegram: "Connect Telegram",
      manageTelegram: "Manage Telegram",
      copyFolderHere: "Copy Folder Here",
      confirm: "Confirm",
      convert: "Convert",
      delete: "Delete",
      downloadMedia: "Download Media",
      editEmojis: "Edit Emojis",
      export: "Export",
      logout: "Logout",
      newPack: "New pack",
      open: "Open",
      openOutputs: "Open Outputs",
      removeIcon: "Remove icon",
      rename: "Rename",
      resync: "Resync",
      retryMedia: "Retry Media",
      setAsIcon: "Set as icon",
      sync: "Sync",
      update: "Update",
      upload: "Upload",
    },
    dialogs: {
      conversionFailed: "Conversion failed",
      editEmojis: "Edit Emojis",
      newPack: "New Pack",
      renameAsset: "Rename Asset",
      renamePack: "Rename Pack",
      telegramPublish: "Telegram Publish",
      telegramSetup: "Telegram Setup",
      packName: "Pack name",
    },
    emptyStates: {
      noAssets: "No assets ・ add files or a folder to get started.",
      noLocalPacks: "No local packs yet",
      noTelegramPacks: "Connect Telegram to load remote sticker packs.",
      noSelection: "Select a pack or create a new one.",
    },
    labels: {
      assets: "Assets",
      emojiList: "Emoji list",
      exportDialogTitle: "Export",
      galleryView: "Gallery view",
      importFolderAsNewPack: "Import folder as new pack",
      listView: "List view",
      localPacks: "Local",
      openContainingFolder: "Open containing folder",
      outputs: "Outputs",
      telegramApiHash: "API hash",
      telegramApiId: "API ID",
      telegramCode: "Login code",
      telegramConnected: "Connected",
      telegramNeedsCode: "Code required",
      stickersNeedEmoji: "Emoji required",
      telegramDisconnected: "Not connected",
      telegramNeedsPassword: "Password required",
      telegramPhoneNumber: "Phone number",
      telegramPassword: "Two-step password",
      telegramNeedsCredentials: "Credentials needed",
      telegramPacks: "Telegram",
      telegramShortName: "Short name",
      telegramTitle: "Title",
    },
    status: {
      starting: "Starting…",
    },
    tooltips: {
      convertAll: "Convert all",
      converting: "Converting…",
      deletePack: "Delete pack",
      deleteTelegramPack: "Deleting Telegram sticker sets is not supported yet",
      noAssetsToConvert: "No assets to convert",
      rename: "Rename",
    },
  },
} as const;

export type AppTokens = typeof appTokens;
